[workspace]
authors = ["mayk <mayk_12@hotmail.com>"]
channels = ["conda-forge"]
name = "Solar-DA-value-EPEX---NED-api"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
requests = ">=2.33.1,<3"
time = ">=1.10,<2"
pandas = ">=3.0.2,<4"
numpy = ">=2.4.3,<3"
